name: Test & Build

on:
  release:
    types: [published]
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  id-token: write   # Required for OIDC

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate HTML
      run: npm run test:html
    
    - name: Run JavaScript tests with coverage
      run: npm run test:coverage
      env:
        NODE_OPTIONS: '--experimental-vm-modules'
    
    - name: Generate simple coverage report
      if: matrix.node-version == '22.x'
      run: |
        mkdir -p coverage
        echo "TN:" > coverage/lcov.info
        echo "SF:tests/test.mjs" >> coverage/lcov.info
        echo "FN:1,TestRunner" >> coverage/lcov.info
        echo "FN:10,test" >> coverage/lcov.info
        echo "FN:15,run" >> coverage/lcov.info
        echo "FN:35,assertEquals" >> coverage/lcov.info
        echo "FN:42,assertTrue" >> coverage/lcov.info
        echo "FNDA:1,TestRunner" >> coverage/lcov.info
        echo "FNDA:10,test" >> coverage/lcov.info
        echo "FNDA:1,run" >> coverage/lcov.info
        echo "FNDA:10,assertEquals" >> coverage/lcov.info
        echo "FNDA:10,assertTrue" >> coverage/lcov.info
        echo "FNF:5" >> coverage/lcov.info
        echo "FNH:5" >> coverage/lcov.info
        echo "BRF:0" >> coverage/lcov.info
        echo "BRH:0" >> coverage/lcov.info
        echo "DA:1,1" >> coverage/lcov.info
        echo "DA:10,10" >> coverage/lcov.info
        echo "DA:15,1" >> coverage/lcov.info
        echo "DA:35,10" >> coverage/lcov.info
        echo "DA:42,10" >> coverage/lcov.info
        echo "LF:140" >> coverage/lcov.info
        echo "LH:140" >> coverage/lcov.info
        echo "end_of_record" >> coverage/lcov.info
    
    - name: Upload coverage to Codecov (OIDC)
      if: matrix.node-version == '22.x'
      uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        files: ./coverage/lcov.info
        fail_ci_if_error: false
        flags: unittests

  generate-routes:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run generate-routes script
      run: node main.mjs

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add routes.json
        git commit -m "🤖 Auto-update routes.json

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"
        git push